/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConectAiRouteImport } from './routes/conect-ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConectAiIndexRouteImport } from './routes/conect-ai.index'
import { Route as ConectAiMedRouteImport } from './routes/conect-ai.med'
import { Route as ConectAiGovRouteImport } from './routes/conect-ai.gov'
import { Route as ConectAiBusinessRouteImport } from './routes/conect-ai.business'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConectAiRoute = ConectAiRouteImport.update({
  id: '/conect-ai',
  path: '/conect-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConectAiIndexRoute = ConectAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConectAiRoute,
} as any)
const ConectAiMedRoute = ConectAiMedRouteImport.update({
  id: '/med',
  path: '/med',
  getParentRoute: () => ConectAiRoute,
} as any)
const ConectAiGovRoute = ConectAiGovRouteImport.update({
  id: '/gov',
  path: '/gov',
  getParentRoute: () => ConectAiRoute,
} as any)
const ConectAiBusinessRoute = ConectAiBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => ConectAiRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conect-ai': typeof ConectAiRouteWithChildren
  '/contato': typeof ContatoRoute
  '/mcp': typeof McpRoute
  '/sobre': typeof SobreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/conect-ai/business': typeof ConectAiBusinessRoute
  '/conect-ai/gov': typeof ConectAiGovRoute
  '/conect-ai/med': typeof ConectAiMedRoute
  '/conect-ai/': typeof ConectAiIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/mcp': typeof McpRoute
  '/sobre': typeof SobreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/conect-ai/business': typeof ConectAiBusinessRoute
  '/conect-ai/gov': typeof ConectAiGovRoute
  '/conect-ai/med': typeof ConectAiMedRoute
  '/conect-ai': typeof ConectAiIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conect-ai': typeof ConectAiRouteWithChildren
  '/contato': typeof ContatoRoute
  '/mcp': typeof McpRoute
  '/sobre': typeof SobreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/conect-ai/business': typeof ConectAiBusinessRoute
  '/conect-ai/gov': typeof ConectAiGovRoute
  '/conect-ai/med': typeof ConectAiMedRoute
  '/conect-ai/': typeof ConectAiIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conect-ai'
    | '/contato'
    | '/mcp'
    | '/sobre'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/conect-ai/business'
    | '/conect-ai/gov'
    | '/conect-ai/med'
    | '/conect-ai/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/mcp'
    | '/sobre'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/conect-ai/business'
    | '/conect-ai/gov'
    | '/conect-ai/med'
    | '/conect-ai'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/conect-ai'
    | '/contato'
    | '/mcp'
    | '/sobre'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/conect-ai/business'
    | '/conect-ai/gov'
    | '/conect-ai/med'
    | '/conect-ai/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConectAiRoute: typeof ConectAiRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  McpRoute: typeof McpRoute
  SobreRoute: typeof SobreRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conect-ai': {
      id: '/conect-ai'
      path: '/conect-ai'
      fullPath: '/conect-ai'
      preLoaderRoute: typeof ConectAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conect-ai/': {
      id: '/conect-ai/'
      path: '/'
      fullPath: '/conect-ai/'
      preLoaderRoute: typeof ConectAiIndexRouteImport
      parentRoute: typeof ConectAiRoute
    }
    '/conect-ai/med': {
      id: '/conect-ai/med'
      path: '/med'
      fullPath: '/conect-ai/med'
      preLoaderRoute: typeof ConectAiMedRouteImport
      parentRoute: typeof ConectAiRoute
    }
    '/conect-ai/gov': {
      id: '/conect-ai/gov'
      path: '/gov'
      fullPath: '/conect-ai/gov'
      preLoaderRoute: typeof ConectAiGovRouteImport
      parentRoute: typeof ConectAiRoute
    }
    '/conect-ai/business': {
      id: '/conect-ai/business'
      path: '/business'
      fullPath: '/conect-ai/business'
      preLoaderRoute: typeof ConectAiBusinessRouteImport
      parentRoute: typeof ConectAiRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConectAiRouteChildren {
  ConectAiBusinessRoute: typeof ConectAiBusinessRoute
  ConectAiGovRoute: typeof ConectAiGovRoute
  ConectAiMedRoute: typeof ConectAiMedRoute
  ConectAiIndexRoute: typeof ConectAiIndexRoute
}

const ConectAiRouteChildren: ConectAiRouteChildren = {
  ConectAiBusinessRoute: ConectAiBusinessRoute,
  ConectAiGovRoute: ConectAiGovRoute,
  ConectAiMedRoute: ConectAiMedRoute,
  ConectAiIndexRoute: ConectAiIndexRoute,
}

const ConectAiRouteWithChildren = ConectAiRoute._addFileChildren(
  ConectAiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConectAiRoute: ConectAiRouteWithChildren,
  ContatoRoute: ContatoRoute,
  McpRoute: McpRoute,
  SobreRoute: SobreRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
